name: Update open house data
on: 
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Scrape and commit
        run: |
          pip install -r requirements.txt
          python -u scrape-openhouse.py
          python -u generate-csv-summary.py
          python -u generate-maps.py

          git config --global user.email "bot@jonty.co.uk"
          git config --global user.name "OH London update GHA"

          git add data
          git add csv
          git add maps
          git commit -m "Automatic OH London data update"

          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
